name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          cd bike && npm ci && cd ../tractor && npm ci
      - name: Build and deploy bike
        run: |
          cd bike && npm run build && mv out ../docs/bike
      - name: Build and deploy tractor
        run: |
          cd tractor && npm run build && mv out ../docs/tractor
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs
